spring:
  application:
    name: doctorcare
  profiles:
    active: local
  doc:
    openapi:
      api-docs:
        path: /api-docs
      swagger-ui:
        path: /swagger-ui.html
logging:
  file:
    name: ${logging.file.path}/${spring.application.name}.log